analysis_and_plot:

  FoodIntake_1hr:
    lmer_formula: "UptakeASum_1hr ~ Genotype * one_hour + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DATBFX_Females_Sable_RC_AL_LD_Food_Intake_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DATBFX_Females_Sable_RC_AL_FoodIntake_1hr_Line_Plot.pdf"
    plot_title: "Food Intake (1hr)"
    plot_type: "line"

  FoodIntake_2hr:
    lmer_formula: "UptakeASum_2hrs ~ Genotype * two_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DATBFX_Females_Sable_RC_AL_LD_Food_Intake_contrasts_2hr.csv"
    plot_output_file: "./output/202305_DATBFX_Females_Sable_RC_AL_FoodIntake_2hr_Line_Plot.pdf"
    plot_title: "Food Intake (2hrs)"
    plot_type: "line"

  FoodIntake_4hrs:
    lmer_formula: "UptakeASum_4hrs ~ Genotype * four_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Food_Intake_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_FoodIntake_4hrs_Line_Plot.pdf"
    plot_title: "Food Intake (4hrs)"
    plot_type: "line"

  Activity_1hr:
    lmer_formula: "AllMeters_1hr ~ Genotype * one_hour + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Activity_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Activity_1hr_Line_Plot.pdf"
    plot_title: "Activity (1hr)"
    plot_type: "line"

  Activity_2hrs:
    lmer_formula: "AllMeters_2hrs ~ Genotype * two_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Activity_contrasts_2hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Activity_2hrs_Line_Plot.pdf"
    plot_title: "Activity (2hrs)"
    plot_type: "line"

  Activity_4hrs:
    lmer_formula: "AllMeters_4hrs ~ Genotype * four_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Activity_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Activity_4hrs_Line_Plot.pdf"
    plot_title: "Activity (4hrs)"
    plot_type: "line"

  Sleep_pct_1hr:
    lmer_formula: "Sleep_pct_1hr ~ Genotype * one_hour + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Sleep_pct_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Sleep_pct_1hr_Line_Plot.pdf"
    plot_title: "Sleep_pct (1hr)"
    plot_type: "line"

  Sleep_pct_2hrs:
    lmer_formula: "Sleep_pct_2hrs ~ Genotype * two_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Sleep_pct_contrasts_2hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Sleep_pct_2hrs_Line_Plot.pdf"
    plot_title: "Sleep_pct (2hrs)"
    plot_type: "line"

  Sleep_pct_4hrs:
    lmer_formula: "Sleep_pct_4hrs ~ Genotype * four_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Sleep_pct_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Sleep_pct_4hrs_Line_Plot.pdf"
    plot_title: "Sleep_pct (4hrs)"
    plot_type: "line"

  Avg_VO2_1hr:
    lmer_formula: "Avg_VO2_1hr ~ Genotype * one_hour + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_VO2_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_VO2_1hr_Line_Plot.pdf"
    plot_title: "Avg_VO2 (1hr)"
    plot_type: "line"

  Avg_VO2_2hrs:
    lmer_formula: "Avg_VO2_2hrs ~ Genotype * two_hours + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_VO2_contrasts_2hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_VO2_2hrs_Line_Plot.pdf"
    plot_title: "Avg_VO2 (2hrs)"
    plot_type: "line"

  Avg_VO2_4hrs:
    lmer_formula: "Avg_VO2_4hrs ~ Genotype * four_hours + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_VO2_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_VO2_4hrs_Line_Plot.pdf"
    plot_title: "Avg_VO2 (4hrs)"
    plot_type: "line"

  Avg_RQ_1hr:
    lmer_formula: "Avg_RQ_1hr ~ Genotype * one_hour + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_RQ_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_RQ_1hr_Line_Plot.pdf"
    plot_title: "Avg_RQ (1hr)"
    plot_type: "line"

  Avg_RQ_2hrs:
    lmer_formula: "Avg_RQ_2hrs ~ Genotype * two_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_RQ_contrasts_2hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_RQ_2hrs_Line_Plot.pdf"
    plot_title: "Avg_RQ (2hrs)"
    plot_type: "line"

  Avg_RQ_4hrs:
    lmer_formula: "Avg_RQ_4hrs ~ Genotype * four_hours + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_RQ_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_RQ_4hrs_Line_Plot.pdf"
    plot_title: "Avg_RQ (4hrs)"
    plot_type: "line"
  
  Avg_EE_1hr:
    lmer_formula: "Avg_EE_1hr ~ Genotype * one_hour + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_EE_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_EE_1hr_Line_Plot.pdf"
    plot_title: "Avg_EE (1hr)"
    plot_type: "line"

  Avg_EE_2hrs:
    lmer_formula: "Avg_EE_2hrs ~ Genotype * two_hours + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_EE_contrasts_2hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_EE_2hrs_Line_Plot.pdf"
    plot_title: "Avg_EE (2hrs)"
    plot_type: "line"

  Avg_EE_4hrs:
    lmer_formula: "Avg_EE_4hrs ~ Genotype * four_hours + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_EE_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_EE_4hrs_Line_Plot.pdf"
    plot_title: "Avg_EE (4hrs)"
    plot_type: "line"

  Tot_EE_1hr:
    lmer_formula: "Tot_EE_1hr ~ Genotype * one_hour + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:one_hour"
    adjust_method: "fdr"
    time_variable: "one_hour"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Tot_EE_contrasts_1hr.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Tot_EE_1hr_Line_Plot.pdf"
    plot_title: "Tot_EE (1hr)"
    plot_type: "line"

  Tot_EE_2hrs:
    lmer_formula: "Tot_EE_2hrs ~ Genotype * two_hours + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:two_hours"
    adjust_method: "fdr"
    time_variable: "two_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Tot_EE_contrasts_2hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Tot_EE_2hrs_Line_Plot.pdf"
    plot_title: "Tot_EE (2hrs)"
    plot_type: "line"

  Tot_EE_4hrs:
    lmer_formula: "Tot_EE_4hrs ~ Genotype * four_hours + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:four_hours"
    adjust_method: "fdr"
    time_variable: "four_hours"
    group_variable: "Genotype"
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Tot_EE_contrasts_4hrs.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Tot_EE_4hrs_Line_Plot.pdf"
    plot_title: "Tot_EE (4hrs)"
    plot_type: "line"

  Activity_LD:
    lmer_formula: "AllMeters_LD ~ Genotype * day_night + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Activity_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Activity_Amount.pdf"
    plot_title: "Light and Dark Activity"
    y_label: "IR Beam Breaks"
    plot_type: "column"

  FoodIntake_LD:
    lmer_formula: "UptakeASum_LD ~ Genotype * day_night + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Food_Intake_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Feeding_Amount.pdf"
    plot_title: "Light and Dark Food Intake"
    y_label: "Food Consumed (g)"
    plot_type: "column"

  Sleep_Percent_LD:
    lmer_formula: "Sleep_pct_LD ~ Genotype * day_night + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Sleep_Percent_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Sleep_Percent_LD.pdf"
    plot_title: "Sleep Percentage (Light and Dark)"
    y_label: "Sleep Percentage (%)"
    plot_type: "column"

  Avg_VO2_LD:
    lmer_formula: "Avg_VO2_LD ~ Genotype * day_night + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_VO2_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Avg_VO2_LD.pdf"
    plot_title: "Average VO2 Consumption (Light and Dark)"
    y_label: "Oxygen Consumption (mL/min)"
    plot_type: "column"

  Avg_EE_LD:
    lmer_formula: "Avg_EE_LD ~ Genotype * day_night + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Avg_EE_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Average_Energy_Expenditure.pdf"
    plot_title: "Light and Dark Average Energy Expenditure"
    y_label: "Energy Expenditure (kcal/hr)"
    plot_type: "column"

  Tot_EE_LD:
    lmer_formula: "Tot_EE_LD ~ Genotype * day_night + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Tot_EE_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_Total_Energy_Expenditure.pdf"
    plot_title: "Light and Dark Cumulative Energy Expenditure"
    y_label: "Energy Expenditure (kcal/hr)"
    plot_type: "column"

  RER_LD:
    lmer_formula: "Avg_RQ_LD ~ Genotype * day_night + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype:day_night"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["day_night", "Genotype"]
    predicted_value_group_cols: ["Animal", "Genotype", "day_night"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_LD_RER_contrasts_LD.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_RER_LD.pdf"
    plot_title: "Light and Dark Average RER"
    y_label: "Average RER (VCO2/VO2)"
    plot_type: "column"

  FoodIntake_Daily:
    lmer_formula: "UptakeASum_Daily ~ Genotype + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Food_Intake_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Feeding_Amount.pdf"
    plot_title: "Daily Food Intake"
    y_label: "Food Consumed (g)"
    plot_type: "column"

  Activity_Daily:
    lmer_formula: "AllMeters_Daily ~ Genotype + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Activity_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Activity_Amount.pdf"
    plot_title: "Daily Activity"
    y_label: "IR Beam Breaks"
    plot_type: "column"

  Sleep_Percent_Daily:
    lmer_formula: "Sleep_pct_Daily ~ Genotype + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Sleep_Percent_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Sleep_Percent.pdf"
    plot_title: "Daily Sleep Percentage"
    y_label: "Sleep Percentage (%)"
    plot_type: "column"

  Avg_VO2_Daily:
    lmer_formula: "Avg_VO2_Daily ~ Genotype + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Avg_VO2_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Avg_VO2.pdf"
    plot_title: "Daily VO2 Consumption"
    y_label: "Oxygen Consumption (mL/min)"
    plot_type: "column"

  RER_Daily:
    lmer_formula: "Avg_RQ_Daily ~ Genotype + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Avg_RQ_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Average_RER.pdf"
    plot_title: "Average Daily RER"
    y_label: "RER (VCO2/VO2)"
    plot_type: "column"

  Avg_EE_Daily:
    lmer_formula: "Avg_EE_Daily ~ Genotype + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Avg_EE_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Average_Energy_Expenditure.pdf"
    plot_title: "Daily Average Energy Expenditure"
    y_label: "Energy Expenditure (kcal/hr)"
    plot_type: "column"

  Tot_EE_Daily:
    lmer_formula: "Tot_EE_Daily ~ Genotype + BodyMass_g + (1|Animal) + (1|StartDate)"
    emm_formula: "pairwise ~ Genotype"
    adjust_method: "fdr"
    group_variable: "Genotype"
    interaction_cols: ["Genotype",]
    predicted_value_group_cols: ["Animal", "Genotype"]
    contrasts_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Tot_EE_contrasts_Daily.csv"
    plot_output_file: "./output/202305_DBFX_Females_Sable_RC_AL_Daily_Total_Energy_Expenditure.pdf"
    plot_title: "Total Daily Energy Expenditure"
    y_label: "Energy Expenditure (kcal)"
    plot_type: "column"