column_value_mappings:
  Genotype:
    source: "Animal"
    target: "Genotype"
    mapping:
      "1": "BKO"
      "2": "Ctrl"
      "3": "BKO"
      "4": "Ctrl"
      "5": "BKO"
      "6": "Ctrl"
      "7": "BKO"
      "8": "Ctrl"
      "9": "BKO"
      "10": "Ctrl"
      "11": "BKO"
      "12": "Ctrl"
      "13": "BKO"
      "14": "Ctrl"
      "15": "BKO"
      "16": "Ctrl"
    default: "Low"
    dtype: str    
  four_hours:
    source: "Cycle"
    target: "four_hours"
    mapping:
      "40": "ZT20_ZT24"
      "32": "ZT16_ZT20"
      "24": "ZT12_ZT16"
      "16": "ZT8_ZT12"
      "8": "ZT4_ZT8"
      "1": "ZT0_ZT4"
    default: "Low"
    dtype: str
  two_hours:
    source: "Cycle"
    target: "two_hours"
    mapping:
      "44": "ZT22_ZT24"
      "40": "ZT20_ZT22"
      "36": "ZT18_ZT20"
      "32": "ZT16_ZT18"
      "28": "ZT14_ZT16"
      "24": "ZT12_ZT14"
      "20": "ZT10_ZT12"
      "16": "ZT8_ZT10"
      "12": "ZT6_ZT8"
      "8": "ZT4_ZT6"
      "4": "ZT2_ZT4"
      "1": "ZT0_ZT2"
    default: "Low"
    dtype: str
  one_hour:
    source: "Cycle"
    target: "one_hour"
    mapping:
      "47": "ZT23"
      "45": "ZT22"
      "43": "ZT21"
      "41": "ZT20"
      "39": "ZT19"
      "37": "ZT18"
      "35": "ZT17"
      "33": "ZT16"
      "31": "ZT15"
      "29": "ZT14"
      "27": "ZT13"
      "25": "ZT12"
      "23": "ZT11"
      "21": "ZT10"
      "19": "ZT9"
      "17": "ZT8"
      "15": "ZT7"
      "13": "ZT6"
      "11": "ZT5"
      "9": "ZT4"
      "7": "ZT3"
      "5": "ZT2"
      "3": "ZT1"
      "1": "ZT0"
    default: "Low"
    dtype: str
  day_night:
    source: "Cycle"
    target: "day_night"
    mapping:
      "25": "Dark"
      "1": "Light"
    default: "Low"
    dtype: str
