general_settings:
  raw_data_path: "C:/Users/nwald/OneDrive/Desktop/202305_Sable_DATBFX_Females_n16_AL_RC/202305_DATBFX_Females_RC_AL_Sable_n16.csv"
  output_path: "C:/src/mice_indirect_calorimetry/output"

data_filters:
  StartDate:
    - '5/22/23'
    - '5/23/23'
    - '5/24/23'
    - '5/25/24'
    - '5/30/23'
